package com.craftinginterpreters.lox;
// generated by GenerateAst.java

abstract class Stmt {

    interface Visitor<R> {
        R visitRiverStmt(River stmt);
    }

    static class River extends Stmt {

        final Token name;
        final Expr.Flow response;
        final Expr inflow;

        River(Token name, Expr.Flow response, Expr inflow) {
            this.name = name;
            this.response = response;
            this.inflow = inflow;
        }

        @Override
        <R> R accept(Visitor<R> visitor) {
            return visitor.visitRiverStmt(this);
        }
    }

    abstract <R> R accept(Visitor<R> visitor);
}
